apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n-ingress-router
  namespace: n8n
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`n8n.lipcloud.org`)
      kind: Rule
      services:
        - name: n8n-service
          port: 5678